services:
  whoami:
    image: "traefik/whoami"  # Minimal container for testing
    container_name: "whoami"
    networks:
      - traefik

networks:
  traefik:
    external: true # Tells the container that this network exist and look for it
