services:
  memcached:
    image: launcher.gcr.io/google/memcached1
    container_name: memcached-container
    ports:
      - "11211:11211"
    networks:
      - traefik

  traefik:
    image: "traefik:v3.2.3"
    container_name: "traefik"
    depends_on:
      - memcached
    ports:  # Maps ports between the host and container
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "8080:8080" # Traefik dashboard
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"  # Configuration file
      - "./acme.json:/acme.json"  # Stores SSL certificates (we can create an empty file and traefik fill it ))
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Enables communication with Docker
      - "./plugins-local/src/github.com/:/plugins-local/src/github.com/" # plugin volumes
      - "./dynamic.yml:/etc/traefik/dynamic.yml:ro"  # Dynamic configuration file (new)

    networks:
      - traefik
networks:
  traefik:
    external: true
