services:
  memcached:
    image: launcher.gcr.io/google/memcached1
    container_name: memcached-container
    ports:
      - "11211:11211"
    networks:
      - traefik

  traefik:
    image: "traefik:v3.2.3"
    container_name: "traefik"
    depends_on:
      - memcached
    command : --configFile=/etc/traefik/traefik.yml
    ports:  # Maps ports between the host and container
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "8080:8080" # Traefik dashboard
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"  # Configuration file
      - "./acme.json:/acme.json"  # Stores SSL certificates (we can create an empty file and traefik fill it ))
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Enables communication with Docker
      - "./plugins-local/src/github.com/ghnexpress/traefik-cache:/plugins-local/src/github.com/ghnexpress/traefik-cache" # plugin volumes

    labels:
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.hashkey.header.enable=true"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.hashkey.header.fields=Token,User-Agent"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.hashkey.header.ignoreFields=X-Request-Id,Postman-Token,Content-Length"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.hashkey.body.enable=false"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.hashkey.method.enable=true"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.memcached.address=memcached-container:11211"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.alert.telegram.chatId=-795576798"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.alert.telegram.token=xxx"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.env=dev"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.forceCache.enable=true"
      - "traefik.http.middlewares.cache-plugin.plugin.memcachedplugin.forceCache.expiredTime=10"
    networks:
      - traefik
networks:
  traefik:
    external: true
    driver: bridge
