entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
log:
  level: ERROR
certificatesResolvers:
  myresolver:
    acme:
      email: mohammad.daneshjoo92@gmail.com
      storage: acme.json
      httpChallenge:
        entrypoint: web

providers:
  docker:
    exposedByDefault: false
  file:  
    filename: "/etc/traefik/dynamic.yml"  # Reference to the dynamic configuration file


api:
  insecure: true
  dashboard: true

experimental:
  localPlugins:
    traefik-api-key-auth:
      moduleName: "github.com/Septima/traefik-api-key-auth"
    memcachedplugin:
      moduleName: "github.com/ghnexpress/traefik-cache"


       